# mixed with code from jhamman
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
env:
  global:
    - HDF5_DISABLE_VERSION_CHECK=1
before_install:
  - sudo apt-get update
  - sudo apt-get install libnetcdf-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create --file .travis-py2.7.yml
  - conda env create --file .travis-py3.6.yml
  - conda env create --file .travis-py3.7.yml
script:
  - gem install narray narray_miss ruby-netcdf minitest rake colorize facets
  - source activate test_env_py27
  - conda update --all
  - cdo -V
  - type -p cdo
  - python --version
  - rake testPython CDO=$(type -p cdo) NO_COLOR=1
  - if test '5' = "$(ruby --version | cut -d ' ' -f 2 | cut -d '.' -f 2)"; then pip uninstall -y netCDF4 xarray -y ; rake testPython CDO=$(type -p cdo) NO_COLOR=1; fi
  - source activate test_env_py36
  - conda update --all
  - cdo -V
  - type -p cdo
  - python --version
  - rake testPython CDO=$(type -p cdo) NO_COLOR=1
  - source activate test_env_py37
  - conda update --all
  - cdo -V
  - type -p cdo
  - python --version
  - rake testPython CDO=$(type -p cdo) NO_COLOR=1
  - if test '5' = "$(ruby --version | cut -d ' ' -f 2 | cut -d '.' -f 2)"; then pip uninstall -y netCDF4 xarray; rake testPython CDO=$(type -p cdo) NO_COLOR=1; fi
  - rake testRuby   CDO=$(type -p cdo) NO_COLOR=1
