# mixed with code from jhamman
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
before_install:
  - sudo apt-get update
  - sudo apt-get install libnetcdf-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create --file .travis-py2.7.yml
  - conda env create --file .travis-py3.6.yml
script:
  - gem install narray narray_miss ruby-netcdf minitest rake
  - source activate test_env_py27
  - cdo -V
  - type -p cdo
  - python --version
  - rake testPython CDO=$(type -p cdo) DEBUG=1
  - source activate test_env_py36
  - cdo -V
  - type -p cdo
  - python --version
  - rake testPython CDO=$(type -p cdo) DEBUG=1
  - rake testRuby   CDO=$(type -p cdo) DEBUG=1
