# mixed with code from jhamman
language: ruby
rvm:
#  - 2.0
#  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.6
  - 2.7
  - 3.0
env:
  global:
    - HDF5_DISABLE_VERSION_CHECK=1
before_install:
  - sudo apt-get update
  - sudo apt-get install libnetcdf-dev
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda info -a
  - conda env create --file .travis-py3.7.yml
script:
  - gem install parallel --version '<= 1.12'
  - gem install narray narray_miss ruby-netcdf minitest rake colorize facets semverse
  - source activate test_env_py37
  - cd ruby; ruby test/test_cdo.rb CDO=$(type -p cdo) NO_COLOR=1
